version: "3.9"
services:
  client:
    container_name: "project-client"
    build:
          context: "./client"
    ports:
      - "3000:3000"

  server:
    container_name: "project-server"
    build:
          context: "./server"
    ports:
      - "5000:5000"
 


 